###
POST https://greetings-api-ir9y.onrender.com/api/greet
content-type: application/json

{
"language": "Xhosa",
"greeting":"Molo"
}
###
POST https://greetings-api-ir9y.onrender.com/api/greet
content-type: application/json

{
"language": "zulu",
"greeting":"sakubona"
}
###
POST https://greetings-api-ir9y.onrender.com/api/greet
content-type: application/json

{
"language": "english",
"greeting":"hello"
}